### PR TITLE
Informal survey  - end stage

### PR DESCRIPTION
**Pull request by sunnychow**

### CODE REVIEW

**Comment by sunnychow** [comment]
@goofyz please verify
the informal survey will go to end stage
and it will not go to ask 2012 question when the user restart the program

**Comment by goofyz** [comment]
The following will be appeared if user continue to input after the survey ended. It should display "你已完成投票, 多謝支持" no matter what input it received after the user completed the survey.

```
Notice: Undefined index: Q16 in C:\Users\goofyz\Dropbox\telegrambot\php\model\state\survey_informal_state.php on line 104

Notice: Undefined index: Q16 in C:\Users\goofyz\Dropbox\telegrambot\php\model\state\survey_informal_state.php on line 90

Notice: Undefined index: Q16 in C:\Users\goofyz\Dropbox\telegrambot\php\model\state\survey_informal_state.php on line 91

Warning: array_chunk() expects parameter 1 to be array, null given in C:\Users\goofyz\Dropbox\telegrambot\php\model\state\survey_informal_state.php on line 91
```

**Comment by sunnychow** [comment]
yup. you are right. 
i have modified  the code. 
it is supported the question without any answer 
for handling the end case

**Comment by goofyz** [comment]
Fix #32, #34 .

**Pull request merged**
